# Generated by Django 4.2.7 on 2024-01-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutions', '0002_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='is_selected',
        ),
        migrations.AddField(
            model_name='tution',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
