# Generated by Django 4.2.7 on 2024-01-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutions', '0003_remove_applicant_is_selected_tution_is_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tution',
            name='is_selected',
        ),
        migrations.AddField(
            model_name='applicant',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
