# Generated by Django 4.2.7 on 2024-01-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_comment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='borrowing_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name='post',
            name='user_reviews',
            field=models.TextField(blank=True, null=True),
        ),
    ]
