# Generated by Django 4.2.7 on 2024-01-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_reviews',
            field=models.TextField(blank=True, null=True),
        ),
    ]
