# Generated by Django 4.2.7 on 2023-12-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_rename_musician_album_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
